export const drawerState = {
    isOpen: false,
}

export const roomState = {
    room: [],
    selected: null,
    floor_selected: null,
    building_selected: null,
    day_selected: 'Sat',
    addPopup:false,
    room_type:"THEORY",
}

export const routineState = {
    rouitne_list: [],
    rouitne_department: null,

}


export const courseState = {
    course_list: [],
    course_offered: [],
    course_department:null,
    course_semester:null,
    course_selected: null
}


export const teacherState = {
    teacher_list: [],
    teacher_selected: null,
    teacher_department:null
}


export const sectionState = {
    section_list: [],
    section_selected: null,
    section_semester:null,
    section_department:null,

}


export const adminStaffState = {
    list: [],
    selected: null,
    iam: null
}

export const routineGetState = {

    teacher: [
        "Md. Fokhray Hossain (MFH)",
        "Mr Mahmudul Hasan (MH)",
        "Dr. Syed Akhter Hossain (SAH)",
        "Dr. Touhid Bhuiyan (DTB)",
        "Mohammad Ismail Jabiullah (MIJ)",
        "Dr. Sheak Rashed Haider Noori (SRH)",
        "Monzur Morshed (MM)",
        "Dr. S M Aminul Haque (SMAH)",
        "Zahid Hasan (ZH)",
        "Nazmun Nessa Moon (NNM)",
        "Fizar Ahmed (FZA)",
        "Md. Aqur Rahman (ATR)",
        "Md Taimur Ahad (MTA)",
        "Naznin Sultana (NS)",
        "Narayan Ranjan Chakraborty (NRC)",
        "Arif Mahmud (AM)",
        "Subhenur Laf (SL)",
        "Md. Sadekur Rahman (SR)",
        "Fahad Faisal (FF)",
        "Abdus Saar (AS)",
        "Shah Md.Tanvir Siddiquee (SMTS)",
        "Moushumi Zaman Bonny (MZB)",
        "Fourcan Karim Mazumder (FKM)",
        "Raja Tariqul Islam (THT)",
        "Md. Abbas Ali Khan (AAK)",
        "Tania Khatun (TK)",
        "Sazzadur Ahamed (SZ)",
        "Faisal Imran (FI)",
        "Saiful Islam (SI)",
        "Taslima Ferdous Shuva (TFS)",
        "Mohammad Monirul Islam (MMI)",
        "Amatul Bushra Akhi (ABA)",
        "Sharmin Akter (SNA)",
        "Dewan Mamun Raza (DMR)",
        "Fatema Tuj Johora (FTJ)",
        "Shayla Sharmin (SS)",
        "Md. Sabab Zulfiker (MSZ)",
        "Amit Chakraborty Chhoton (ACC)",
        "Mushfiqur Rahman (MUR)",
        "Md. Hafizul Imran (MHI)",
        "Tapasy Rabeya (TRA)",
        "Aliza Ahmed Khan (AAKN)",
        "Zerin Nasrin Tumpa (ZNT)",
        "Mohammad Jahangir Alam (MJA)",
        "Refath Ara Hossain (RAH)",
        "Firoz Hasan (FH)",
        "Md. Aynul Hasan Nahid (AHN)",
        "Nishat Sultana (NIS)",
        "Isha Nowrin (IN)",
        "Lamia Rukhsara (LR)",
        "Israt Jahan (IJN)",
        "Zakia Sultana (ZS)",
        "Sharun Akter Khushbu (SAK)",
        "Abu Kaisar Mohammad Masum (KMM)",
        "Md. Assaduzzaman (MA)",
        "Amir Sohel (ARS)",
        "Md. Zabirul Islam (MZI)",
        "Fabliha Haque (FHE)",
        "Nahid Hasan (NH)",
        "Md. Ferdouse Ahmed Foysal (FAF)",
        "Johora Akter Polin (JAP)",
        "Aal Hossan Sarower (AHS)",
        "Chowdhury Abida Anjum Era (CAA)",
        "Md. Mafiul Hasan Man (MHM)",
        "Tanim Ahmed (TA)",
        "Krishno Dey (KD)",
        "Abdullah Al Mamun (AAM)",
        "Partha Dip Sarkar (PDS)",
        "Md. Moynul Hossain (MMH)",
        "Nushrat Jahan Ria (NJR)",
        "Md. Mahedi Hassan (MHS)",
        "Taslima Tabassum (TT)",
        "Faria Nishat Khan (FNK)",
        "Mahimul Islam Nadim (MIN)",
        "Md Umaid Hasan (MUH)",
        "Mayen Uddin Mojumdar (MUM)",
        "Golam Rabbany (GR)",
        "Zahura Zaman (ZZ)",
        "Nasima Islam Bithi (NIB)",
        "Md. Ashraful Islam Talukder (MAIT)",
        "MD. Hasanuzzaman Dipu (MHD)",
        "Md. Ali Hossain (MAH)",
        "Shahadat Hossain (SH)",
        "Dris Saha (DS)",
        "Zannatul Mawa Koli (ZMK)",
        "Md. Monarul Islam (MIS)",
        "Tanvirul Islam (TI)",
        "Md. Nahid Hasan (MNH)",
        "Sultan Mahmud (SM)",
        "Rahmatul Kabir Rasel Sarker (RKR)",
        "Nusrat Khan (NK)",
        "Md Ak Asif Khan Akash (AAKA)",
        "Md. Mubtasim Fuad (MMF)",
        "Mohammad Asifur Rahim (MSRM)",
        "Md. Mizanur Rahman (MMRN)",
        "Umme Ayman (UA)",
        "Md. Shakhawath Hossain (MSHN)",
        "Umme Habiba (UH)",
        "Munira Ferdous (MNF)",
        "Mr. Mohammad Abdul Halim (ALH)",
        "Md. Tazmim Hossain (TH)",
        "K. M. Shahriar Islam (KMSI)",
        "Lameya Islam (LI)",
        "Hasnur Jahan (HJ)",
        "Md. Jakaria Zobair (MJZ)",
        "Sinthia Chowdhury (SCH)",
        "Farjana Akhter (FA-C)",
        "Shahriar Shakil (MSS)",
        "Abu Sufian (ASN)",
        "Md. Arid Hasan (MAHN)",
        "Md. Shovon (MDSH)",
        "Md. Fahad Hossain (FHN)",
        "Md. Hasan Imam Bijoy (MHIM)",
        "Deawan Rakin Ahamed Remal (DRAR)",
        "Onamika Islam (OI)",
        "Mosharraf Hossain Khan (MHK)",
        "Md. Nazmul Islam (MNI)",
        "Zarin Anjuman Sehu (ZAS)",
        "Mst. Mostary Begum (MB)",
        "Sakib Mahmood Chowdhury (SMC)",
        "Nasrin Akter (NAA)",
        "Takowa Rahman (TR)",
        "Jakia Akter (ZA)",
        "Dewan Ashiquzzaman Almas (DAA)",
        "Md. Asif Mahmud Ridoy (MAMR)",
        "Md. Maynul Islam (MMIM)",
        "Mehedi Hasan (MHHN)",
        "Dara Bin Zaid (DBZ)",
        "Nusrat Nabi (NB)",
        "Meherunnesa Tania (MT)",
        "Tasmiah Rahman (TRN)",
        "Md. Rafidul Hasan Khan (RHK)",
        "Tanveer Hasan (THN)",
        "Umme Sanzida Afroz (USA)",
        "Mostak Ahmad (MKA)",
        "Tanvir Rahman (TRR)",
        "Md. Abdul Hye Zebon (MAHZ)",
        "Rashidul Hasan Hridoy (RHH)",
        "Md. Rasedul Islam (MRIS)",
        "Nusrat Sultana (NST)",
        "Md. Rezwanul Islam (MRI)",
        "Md Ziaul Haque Zim (ZHZ)",
        "Khairun Nahar (KN)",
        "Afsana Jerin Shayary (AJS)",
        "Mahmudul Hasan (MH)",
        "Nahida Akter Poly (NAP)",
        "Md. Rafiz Uddin (MRU)",
        "Afroza Akter (AA)",
        "Shipra Mondal (SML)",
        "Mahinur Akther (MA*)",
        "Razia Sultana (RS)",
        "Zannatul Ferdous (ZF)",
        "Dr. Bimal Chandra Das (BCD)",
        "Mohammad Salek Parvez (SP)",
        "Masuma Parvin (MPL)",
        "Mohammad Abdul Halim (MAH*)",
        "Proma Dash (PD)",
        "Dr. Md. Kamrul Hossain (DMKH)",
        "Aa Sanjida Talukder (AST)",
        "Shirin Sultana (SS*)",
        "Mst. Sanjida Afrin (MSA)",
        "Khadijatul Kobra (KK)",
        "Md. Shakib Hossain (MSH)",
        "Farzana Afrin Mim (FAM)",
        "Sujoy Devnath (SD)",
        "Md. Mizanur Rahman (MR)",
        "Md. Mozammelul Haque (MMH*)",
        "Md. Hasibur Rahaman Peash (HRP)",
        "Dr. Sk. Abdul Kader Arafin (AKA)",
        "Mohammed Riaz Rahman Munna (MRRM)",
        "Shahina Haque (SHA)",
        "Md. Yousuf Ali (MYA)",
        "Md. Masum Sarker (MMS)",
        "Farhana Tania (FT)",
        "Md. Mehedi Hasan (MEH)",
        "Sumaiya Begum (SB)",
        "Md. Yousuf Ali (YA)",
        "Nishat Tasnim (NT)",
        "Md. Abedullah (MMA)",
        "Dr. Md.Samaun Hasan (MSH*)",
        "Shakil Ahmed (SA)",
        "Sumaia Akhter (SAA)",
        "Abu Shahed Shah Md Nazmul Arefin (ASNA)",
        "Munmun Shabnam Bipasha (MSB)",
        "Sayeda Maria Rahman (SMR)",
        "Rokunuzzaman Biswas (RB)",
        "Nazmul Huda Azad (NHA)",
        "Abdullah Al Mahmud (AAM*)",
        "Md. Al Imran (AI)",
        "Md. Khaled Sifullah (MKS)",
        "Sonia Akter (SAR)",
        "Md. Salman Sohel (SAS)",
        "Shithee Ahmed (SAH)",
        "Mr. Rokunuzzaman Biswas (RKB)",
        "Professor A. M.M. Hamidur Rahman (HR)",
        "Dr. Liza Sharmin (LS)",
        "Dr. Binoy Barman (BB)",
        "Dr.Mohammed Shamsul Hoque (SH)",
        "Mr. Mohammad Mustafizur Rahman Sameen (MRS)",
        "Ms. Irina Ishrat (IR)",
        "Ms. Nahid Kaiser (NK)",
        "Dr. Md. Mostafa Rashel (MMR)",
        "Ms. Asma Alam (AA)",
        "Mr. Md. Ariful Islam Laskar (MAIL)",
        "Ms. Rabeya Binte Habib (RBH)",
        "Ms. Fatema Begum Laboni (FBL)",
        "Md. Nuruzzaman Moral (NM)",
        "Mr. Mohammad Elius Hossain (MEH)",
        "Mr. Md Abdul Momen Sarker (AMS)",
        "Dr. Ehatasham Ul Hoque Eiten (EHE)",
        "Ms. Afroza Akhter Tina (AAT)",
        "Ms. Shipra Mondal (SM)",
        "Mr. Mohammad Zahidul Islam (MZI)",
        "Mr. Al Mahmud Rumman (AMR)",
        "Md Shohidul Islam Polash (SIP)",
        "Md. Maruf Chand (MMC)",
        "Mr. Md Jihan Parvaj (MJP)",
        "Abdul Muntakin (ALM)",
        "Mr. Mahmudul Islam Rakib (MIR)",
        "Ms Sadia Jannat Mitu (SAJ)",
        "Mansura Akter Mome (MAM)",
        "Ms Faiza Feroz (FFZ)",
        "Mr. Istiaque Ahmed (IAD)",
        "Durjoy Bhowmik (DJB)",
        "Gayatri Rani Sarker (GRS)",
        "Chayti Saha (CSA)",
        "Md. Roni Islam (RIM)",
        "Md. Suzauddulah (SDH)",
        "Md. Al-Mamun (AMN)",
        "Tania Akter Asa (TAA)",
        "Mr. Abdus Sattar (AS)",
        "Afsana Begum (ABM)",
        "Avizit Nandi (ATN)",
        "Md. Emad Hossain Likhon (EHL)"
    ],

    course: ["Digital Image Processing", "Big Data & IoT", "Big Data & IoT Lab", "Software Engineering", "Algortithm", "Algorithm Lab"],
    section: [
        "56_A",
        "56_B",
        "56_C",
        "56_D",
        "56_E",
        "56_F",
        "57_A",
        "57_B",
        "57_C",
        "57_D",
        "58_A",
        "58_B",
        "58_C",
        "58_D",
        "58_E",
        "59_A",
        "59_B",
        "59_C",
        "59_D",
        "60_A",
        "60_B",
        "60_C",
        "60_D",
        "60_E",
        "60_F",
        "60_G",
        "60_H",
        "60_I",
        "61_A",
        "61_B",
        "61_C",
        "61_D",
        "61_E",
        "61_F",
        "61_G",
        "61_H",
        "61_I",
        "61_J",
        "61_K",
        "61_L",
        "61_M",
        "61_N",
        "61_O",
        "61_P",
        "61_Q",
        "61_R",
        "61_S",
        "61_T",
        "61_U",
        "61_V",
        "61_W",
        "61_X",
        "61_Y",
        "61_Z",
        "62_A",
        "62_B",
        "62_C",
        "62_D",
        "62_E",
        "62_F",
        "62_G",
        "62_H",
        "63_A",
        "63_B",
        "63_C",
        "63_D",
        "63_E",
        "63_F",
        "63_G",
        "63_H",
        "63_I",
        "63_J",
        "63_K",
        "63_L",
        "63_M",
        "63_N",
        "63_O",
        "63_P",
        "63_Q",
        "63_R",
        "63_S",
        "63_T",
        "63_U",
        "63_V",
        "63_W",
        "63_X",
        "63_Y",
        "63_Z",
        "64_A",
        "64_B",
        "64_C",
        "64_D",
        "64_E",
        "64_F",
        "64_G",
        "64_H",
        "64_I",
        "64_J",
        "64_K",
        "64_L",
        "64_M",
        "64_N",
        "64_O",
        "64_P",
        "64_Q",
        "64_R",
        "64_S",
        "64_T",
        "64_U",
        "64_V",
        "64_W",
        "64_X",
        "64_Y",
        "64_Z",
        "65_A",
        "65_B",
        "65_C",
        "65_D",
        "65_E",
        "65_F",
        "65_G",
        "65_H",
        "65_I",
        "65_J",
        "65_K",
        "65_L",
        "65_M",
        "65_N",
        "65_O",
        "65_P",
        "65_Q",
        "65_R",
        "65_S",
        "65_T",
        "65_U",
        "65_V",
        "65_W",
        "65_X",
        "65_Y",
        "65_Z",
        "66_A",
        "66_B",
        "66_C",
        "66_D",
        "66_E",
        "66_F",
        "66_G",
        "66_H",
        "66_I",
        "66_J",
        "66_K",
        "66_L",
        "66_M",
        "66_N",
        "66_O",
        "66_P",
        "66_Q",
        "66_R",
        "66_S",
        "66_T",
    ],
    room: [
        "KT-201",
        "KT-208",
        "KT-213",
        "KT-216",
        "KT-217",
        "KT-218",
        "KT-219",
        "KT-220",
        "KT-221",
        "KT-222",
        "KT-223",
        "KT-224",
        "KT-302",
        "KT-303",
        "KT-304",
        "KT-305",
        "KT-306",
        "KT-307",
        "KT-318(A)",
        "KT-318(B)",
        "KT-320",
        "KT-801(A)",
        "KT-801(B)",
        "KT-802",
        "KT-803",
        "KT-804",
        "KT-813(B)",
        "KT-514",
        "KT-515",
        "KT-516",
        "KT-518",
        "KT-916",
        "KT-919",
        "KT-1404",
        "G1-025",
        "G1-026",
        "G1-027",
        "KT-501(A) (COM LAB)",
        "KT-501(B) (COM LAB)",
        "KT-503 (COM LAB)",
        "KT-504 (COM LAB)",
        "KT-510 (COM LAB)",
        "KT-513 (COM LAB)",
        "G1-001 (COM LAB)",
        "G1-002 (COM LAB)",
        "G1-003 (COM LAB)",
        "G1-004 (COM LAB)",
        "G1-005 (COM LAB)",
        "G1-006 (COM LAB)",
        "G1-007 (COM LAB)",
        "G1-008 (COM LAB)",
        "G1-009 (COM LAB)",
        "G1-010 (COM LAB)",
        "G1-011 (COM LAB)",
        "G1-012 (COM LAB)",
        "G1-013 (COM LAB)",
        "G1-014 (COM LAB)",
        "G1-016 (COM LAB)",
        "G1-017 (COM LAB)",
        "G1-018 (COM LAB)",
        "G1-020 (COM LAB)",
        "G1-021 (COM LAB)",
        "G1-022 (COM LAB)",
        "KT-809 (E.C. & D.E. Lab)",
        "KT-810 (E.C. & B.E. Lab)",
        "EMBED LAB",
        "IOT LAB",
        "ECLAB-105 (EEE)",
        "ECLAB-106 (EEE)",
        "KT-815 (Physics Lab)",
        "KT-816 (Physics Lab)",
    ]
}

export const generateState = {
    faculty: [],
    activeTeacher: null,
    offered: [],
    next: false,
    edit: false,
    add: false,
    offer_selected_section:null,
    offer_selected_course:null,
    offer_routine_day:null,
    offer_routine_room:null,
}