export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";

export const GENERATE_FACULTY_LIST = "GENERATE_FACULTY_LIST";
export const GENERATE_SELECT_FACULTY = "GENERATE_SELECT_FACULTY";
export const GENERATE_DESELECT_FACULTY = "GENERATE_DESELECT_FACULTY";
export const GENERATE_NEXT_ENABLE = "GENERATE_NEXT_ENABLE";
export const GENERATE_NEXT_DISABLE = "GENERATE_NEXT_DISABLE";
export const GENERATE_EDIT_ENABLE = "GENERATE_EDIT_ENABLE";
export const GENERATE_EDIT_DISABLE = "GENERATE_EDIT_DISABLE";
export const GENERATE_ADD_ENABLE = "GENERATE_ADD_ENABLE";
export const GENERATE_ADD_DISABLE = "GENERATE_ADD_DISABLE";

export const GENERATE_FACULTY_OFFERED = "GENERATE_FACULTY_OFFERED";
export const GENERATE_FACULTY_REMOVE_OFFERED = "GENERATE_FACULTY_REMOVE_OFFERED";

export const SEMESTER_FACULTY = "SEMESTER_FACULTY";
export const SEMESTER_COURSE = "SEMESTER_COURSE";
export const SEMESTER_SECTION = "SEMESTER_SECTION";
export const SEMESTER_ROOM = "SEMESTER_ROOM";

export const SEMESTER_ROUTINE = "SEMESTER_ROUTINE";
