export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";

export const GENERATE_FACULTY_LIST = "GENERATE_FACULTY_LIST";
export const GENERATE_SELECT_FACULTY = "GENERATE_SELECT_FACULTY";
export const GENERATE_DESELECT_FACULTY = "GENERATE_DESELECT_FACULTY";
export const GENERATE_NEXT_ENABLE = "GENERATE_NEXT_ENABLE";
export const GENERATE_NEXT_DISABLE = "GENERATE_NEXT_DISABLE";
export const GENERATE_EDIT_ENABLE = "GENERATE_EDIT_ENABLE";
export const GENERATE_EDIT_DISABLE = "GENERATE_EDIT_DISABLE";
export const GENERATE_ADD_ENABLE = "GENERATE_ADD_ENABLE";
export const GENERATE_ADD_DISABLE = "GENERATE_ADD_DISABLE";

export const GENERATE_FACULTY_OFFERED = "GENERATE_FACULTY_OFFERED";
export const GENERATE_FACULTY_REMOVE_OFFERED = "GENERATE_FACULTY_REMOVE_OFFERED";

export const SECTION_LIST = "SECTION_LIST";
export const SECTION_SELECTED = "SECTION_SELECTED";
export const SECTION_SEMESTER = "SECTION_SEMESTER";
export const SECTION_DEPARTMENT = "SECTION_DEPARTMENT";


export const ROOM_LIST = "ROOM_LIST";
export const ROOM_SELECTED = "ROOM_SELECTED";
export const BUILDING_ROOM = "BUILDING_ROOM";
export const FLOOR_ROOM = "FLOOR_ROOM";
export const SELECTED_DAY_ROOM = "SELECTED_DAY_ROOM";
export const SELECTED_TYPE_ROOM = "SELECTED_TYPE_ROOM";


export const TEACHER_LIST = "TEACHER_LIST";
export const TEACHER_SELECTED = "TEACHER_SELECTED";
export const TEACHER_DEPARTMENT = "TEACHER_DEPARTMENT";
