export const DRAWER_OPEN = "DRAWER_OPEN";
export const DRAWER_CLOSE = "DRAWER_CLOSE";

export const ROUTINE_GENERATE_FACULTY = "ROUTINE_GENERATE_FACULTY";
export const ROUTINE_GENERATE_SECTION = "ROUTINE_GENERATE_SECTION";
export const ROUTINE_GENERATE_COURSE = "ROUTINE_GENERATE_COURSE";
export const ROUTINE_GENERATE_ASSIGN = "ROUTINE_GENERATE_ASSIGN";

export const SEMESTER_FACULTY = "SEMESTER_FACULTY";
export const SEMESTER_COURSE = "SEMESTER_COURSE";
export const SEMESTER_SECTION = "SEMESTER_SECTION";
export const SEMESTER_ROOM = "SEMESTER_ROOM";

export const SEMESTER_ROUTINE = "SEMESTER_ROUTINE";
